thirty_six_fair_unfair=[ 
"The baby smiled at the father",
"The man excused the visitor",
"The lecturer amused the students",
"The woman picnicked with the man",
"The nurse snuggled the baby",    
"Jim hugged Sara",
"The workers savoured the food",
"The man serenaded his fiancé",
"The groom serenaded the bride",
"The president welcomed the immigrant",
"The student appreciated the tutor's help",
"The crowd acclaimed the singer", 
"The audience enjoyed the tenor",
"The principal thanked the student",
"Jack celebrated with Jill",
"The teacher loved the pupils",
"The nanny comforted the child",
"Tom charmed the woman",
"The footballer damaged the goalkeeper",
"The man harmed the lady",
"The teenager slandered the attendant",
"The student slurred the teacher",
"The killer disfigured the person",
"The saboteur contaminated the people",
"The guard dehumanized the boy",
"The spy poisoned the innocent",
"The father murdered the boy",
"The attendant misinformed the customer",
"The man demonized the people",
"The woman assaulted the baby",
"The man sickened the lady",
"The organizer mismanaged the crowd",
"Richard brutalized Noah",
"The escapee raped the policeman",  
"The army slaughtered the children", 
"The teacher crippled the student"    
]